The purpose of the project is to learn the mapping from polar coordinates to a a discrete 10x10 grid of cells in the plane, using a neural network. 

The supervised dataset is given to you in the form of a generator (to be considered as a black box).

The model must achieve an accuracy of 95%, and it will be evaluated in a way **inversely proportional to the number of its parameters: the smaller, the better.**

**WARNING**: Any solution taking advantage of meta-knowledge about the generator will be automatically rejected.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Reshape, concatenate
from tensorflow.keras.models import Model

Here is the generator. It returns triples of the form ((theta,rho),out) where (theta,rho) are the polar coordinates of a point in the first quadrant of the plane, and out is a 10x10 map with "1" in the cell corresponding to the point position, and "0" everywhere else.

By setting flat=True, the resulting map is flattened into a vector with a single dimension 100. You can use this variant, if you wish. 

In [2]:
def polar_generator(batchsize,grid=(10,10),noise=.002,flat=False):
  while True:
    x = np.random.rand(batchsize)
    y = np.random.rand(batchsize)
    out = np.zeros((batchsize,grid[0],grid[1]))
    xc = (x*grid[0]).astype(int)
    yc = (y*grid[1]).astype(int)
    for b in range(batchsize):
      out[b,xc[b],yc[b]] = 1
    #compute rho and theta and add some noise
    rho = np.sqrt(x**2+y**2) + np.random.normal(scale=noise)
    theta = np.arctan(y/np.maximum(x,.00001)) + np.random.normal(scale=noise)
    if flat:
      out = np.reshape(out,(batchsize,grid[0]*grid[1]))
    yield ((theta,rho),out)

Let's create an instance of the generator on a grid with dimension 3x4

In [ ]:
g1,g2 = 3,4
gen = polar_generator(1,grid=(g1,g2),noise=0.0)

And now let's see a few samples.

In [ ]:
(theta,rho),maps = next(gen)
for i,map in enumerate(maps):
  #let us compute the cartesian coordinates
  x = np.cos(theta[i])*rho[i]
  y = np.sin(theta[i])*rho[i]
  print("x coordinate (row): {}".format(int(x*g1)))
  print("y coordinate (col): {}".format(int(y*g2)))
  print("map:")
  print(np.reshape(map,(g1,g2)))

x coordinate (row): 0
y coordinate (col): 1
map:
[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Exercise: add noise to the generator, and check the effect on the "ground truth".

# What to deliver

For the purposes of the project you are supposed to work with the **default 10x10 grid, and the default noise=.002**

The generator must be treatead as a black box, do not tweak it, and do not exploit its semantics that is supposed to be unknown. You are allowed to work with the "flat" modality, if you prefer so.

You need to:
1.   define an accuracy function (take inspiration from the code of the previous cell)
2.   define a neural network taking in input theta and rho, and returning out
3. measure the network's accuracy that must be above 95% (accuracy must be evaluated over at least 20000 samples)
4. tune the network trying to decrease as much as possible the numer of parameters, preserving an accuracy above 95%. Only your best network must be delivered.

You must deliver a SINGLE notebook working on colab, containing the code of the network, its summary, the training history, the code for the accurary metric and its evaluation on the network.

**N.B.** The accuracy must be above 95% but apart from that it does not influence the evaluation. You score will only depend on the number of parameters: the lower, the better.

#Good work!





In [3]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.experimental import AdamW
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import ReLU, LeakyReLU, Dropout

# Model

In [ ]:
def get_unit(n: int):
  res = 1
  while(2^res < n):
    res += 1
  return res

In [ ]:
def get_network_old(output_shape=(10,10)):
  #theta, ro = theta_ro
  out1, out2 = output_shape
  out_area = out1 * out2

  input1 = Input(shape=(1,))
  input2 = Input(shape=(1,))
  merged = concatenate([input1, input2])

  d1 = Dense(48)(merged)
  d1 = LeakyReLU()(d1)
  d1 = Dense(32)(d1)
  d1 = LeakyReLU()(d1)
  d1 = Dropout(0.1)(d1)
  d2 = Dense(out_area, activation='softmax')(d1)
  
  model = Model(inputs=[input1, input2], outputs=d2)
  print(model.summary())
  return model



## New network
The input is a tuple containing theta and rho. Rho is processed by a single Dense layer (with a single unit) to rescale the input, instead theta is processed two times in parallel by two Dense layer each time (this is done in order to extract the sin and the cosin). Then we merge the new theta with the sin and the cosin, and those layers are processed in parallel by two stack of two Dense layer (each having 10 units) in order to extract informations about the x and the y axis. Then those outputs are merged together and the information is processed by a stack of Dense layer composed by two layers having 20 units and a last layer of 100 units to produce the output.
The activaction function used are all ReLUs, but in the last layer is used a sigmoid to obtain the probability that in each grid of the map there will be a 1.

In [20]:
def get_network(output_shape=(10,10)):
  #theta, ro = theta_ro
  out1, out2 = output_shape
  out_area = out1 * out2

  input1 = Input(shape=(1,))
  input2 = Input(shape=(1,))

  x1 = Dense(1)(input1)
  x1 = ReLU()(x1)
  x1 = Dense(1)(x1)
  x1 = ReLU()(x1)

  x2 = Dense(1)(input1)
  x2 = ReLU()(x2)
  x2 = Dense(1)(x2)
  x2 = ReLU()(x2)

  x3 = Dense(1)(input2)
  x3 = ReLU()(x3)

  merged1 = concatenate([x1, x3])
  merged2 = concatenate([x2, x3])

  d1 = Dense(10)(merged1)
  d1 = ReLU()(d1)
  d1 = Dense(10)(d1)
  d1 = ReLU()(d1)
  d2 = Dense(10)(merged2)
  d2 = ReLU()(d2)
  d2 = Dense(10)(d2)
  d2 = ReLU()(d2)
  
  merged3 = concatenate([d1,d2])
  d3 = Dense(20)(merged3)
  d3 = ReLU()(d3)
  d3 = Dense(20)(d3)
  d3 = ReLU()(d3)
  
  d3 = Dense(out_area, activation='softmax')(d3)
  
  model = Model(inputs=[input1, input2], outputs=d3)
  print(model.summary())
  return model

In [23]:
net = get_network(output_shape=(10,10))
learning_rate = 1e-3
weight_decay = 1e-4

net.compile(
    optimizer=Adam(learning_rate=learning_rate),
    loss=CategoricalCrossentropy()
)


Model: "model_7"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_15 (InputLayer)          [(None, 1)]          0           []                               
                                                                                                  
 dense_63 (Dense)               (None, 1)            2           ['input_15[0][0]']               
                                                                                                  
 dense_65 (Dense)               (None, 1)            2           ['input_15[0][0]']               
                                                                                                  
 re_lu_56 (ReLU)                (None, 1)            0           ['dense_63[0][0]']               
                                                                                            

In [24]:
BATCH_SIZE = 2048

callback = EarlyStopping(monitor="loss",
    min_delta=0.0005,
    patience=20,
    restore_best_weights=True)

# history = net.fit_generator(polar_generator(BATCH_SIZE), steps_per_epoch=1000, epochs=10)
history = net.fit(polar_generator(BATCH_SIZE, flat=True), batch_size = BATCH_SIZE, steps_per_epoch=1000, epochs=1000, callbacks=[callback])

Epoch 1/1000
1000/1000 [==============================] - 15s 12ms/step - loss: 2.9679
Epoch 2/1000
1000/1000 [==============================] - 11s 11ms/step - loss: 1.9547
Epoch 3/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.9172
Epoch 4/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.5613
Epoch 5/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.4060
Epoch 6/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.3345
Epoch 7/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.2939
Epoch 8/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.2671
Epoch 9/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.2476
Epoch 10/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.2344
Epoch 11/1000
1000/1000 [==============================] - 12s 12ms/step - loss: 0.2207
Epoch 12/1000
1000/1000 [================

In [25]:
def get_accuracy(net, gen, sample=1000):
  (theta,rho),maps = next(gen)
  pred = net.predict((theta,rho))

  ok = 0
  for i in range(sample):
    if np.argmax(maps[i]) == np.argmax(pred[i]):
      ok += 1

  return ok*100/sample

In [18]:
def get_accuracy2(net, gen, sample=1000, shape=(10,10)):
  (theta,rho),maps = next(gen)
  pred = net.predict((theta,rho))

  accuracy = 0
  
  for i in range(sample):
    max_true = np.argmax(maps[i])
    x_true = max_true//10
    y_true = max_true%10
    
    max_pred = np.argmax(pred[i])
    x_pred = max_pred//10
    y_pred = max_pred%10

    accuracy += (1 - (np.square(x_true - x_pred) + np.square(y_true - y_pred)) / (shape[0]*np.sqrt(2)))

  return accuracy*100/sample

In [30]:
sample = int(10e5)
get_accuracy(net, polar_generator(sample, grid=(10,10), flat=True), sample=sample)

31250/31250 [==============================] - 53s 2ms/step


93.1657

In [ ]:
get_accuracy2(net, polar_generator(sample, grid=(10,10), flat=True), sample=sample)

1563/1563 [==============================] - 2s 1ms/step


99.70485362953092